name: Update Holidays

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  download:
    name: download and check changes
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.filter.outputs.changed }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download latest csv
        run: ./scripts/update_holidays.sh

      - name: check changes
        id: filter
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  commit:
    name: build and commit
    needs: download
    if: ${{ needs.download.outputs.changed == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download latest csv
        run: ./scripts/update_holidays.sh

      - name: increment version
        id: increment_version
        run: |
          RESULT=$(./scripts/increment_version.sh)
          echo "version=${RESULT}" >> "$GITHUB_OUTPUT"

      - name: build repository
        run: ./gradlew publishReleasePublicationToRepositoryRepository

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "v${{ steps.increment_version.outputs.version }}"

      - name: tag
        run: |
          git tag v${{ steps.increment_version.outputs.version }}
          git push origin v${{ steps.increment_version.outputs.version }}
